apiVersion: v1
kind: Endpoints
metadata:
  name: ttnrdunr
  namespace: thingstack
subsets:
  - addresses:
    - ip: 172.20.199.164
    ports:
    - port: 80
      name: thingstackout
      protocol: TCP
    - port: 443
      name: thingstackssl
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ttnrdunr
  namespace: thingstack
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: thingstackout
    - protocol: TCP
      port: 443
      targetPort: 443
      name: thingstackssl
  type: ClusterIP
  clusterIP: None
    #externalTrafficPolicy: Cluster
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ttnrdunr-web-ui
  namespace: thingstack
  annotations:
    #kubernetes.io/ingress.class: nginx
    #cert-manager.io/issuer: selfsigned-cluster-issuer
    #cert-manager.io/issuer: letsencrypt
    #cert-manager.io/issuer-kind: ClusterIssuer
    #acme.cert-manager.io/http01-ingress-class: traefik
    #traefik.ingress.kubernetes.io/redirect-entry-point: https
    #traefik.ingress.kubernetes.io/redirect-permanent: "true"
    #ingress.kubernetes.io/ssl-redirect: "true"
    #ingress.kubernetes.io/ssl-temporary-redirect: "false"
    #ingress.kubernetes.io/ssl-per
    #nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    #nginx.ingress.kubernetes.io/proxy-redirect-from: ncar-da-15.rc.unr.edu/ttn
    #nginx.ingress.kubernetes.io/proxy-redirect-to: ttn.rd.unr.edu/$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    #nginx.ingress.kubernetes.io/x-forwarded-prefix: "/ttn"
    #nginx.ingress.kubernetes.io/app-root: /$2
    #nginx.ingress.kubernetes.io/app-root: /grafana
    #use-port-in-redirects: "true"

spec:
  ingressClassName: nginx
  rules:
  - host: ncar-da-15.rc.unr.edu
    http:
      paths:
      - path: "/ttn(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: ttnrdunr
            port:
              number: 80
  - http:
      paths:
      - path: "/tts(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: ttnrdunr
            port:
              number: 80
      - path: "/console" #"(/|$)(.*)"
        pathType: Prefix #ImplementationSpecific
        backend:
          service:
            name: ttnrdunr
            port:
              number: 80
      - path: "/assets" #"(/|$)(.*)"
        pathType: Prefix #ImplementationSpecific
        backend:
          service:
            name: ttnrdunr
            port:
              number: 80
      - path: "/oauth" #"(/|$)(.*)"
        pathType: Prefix #ImplementationSpecific
        backend:
          service:
            name: ttnrdunr
            port:
              number: 80
      - path: "/api" #"(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: ttnrdunr
            port:
              number: 80
  #tls:
  #- hosts:
  #  - ncar-da-15.rc.unr.edu
  #  secretName: acme-account-key

