apiVersion: batch/v1
kind: CronJob
metadata:
  name: backuppostgresql
  namespace: thingstack
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - -c
            #- pg_basebackup -v -h thingstackinstance-rw.thingstack -p 5432 -U postgres -D /backups/globuspostgre/$(date
            #  '+%F_%H%M%S')backup --progress -W -d postgresql://postgres@135.197.75.31:31997/postgres
            #  -Z 6 -F tar
            - echo "hello world"
            command:
            - bash
            env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: thingstackinstance-superuser
            - name: POSTGRES_HOST
              value: thingstackinstance-rw.thingstack.svc.cluster.local
            image: postgres:16
            imagePullPolicy: IfNotPresent
            name: postgrebackup
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /backups
              name: backups
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - persistentVolumeClaim:
              claimName: database-pv
            name: backups
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: "2024-04-09T00:00:00Z"
  lastSuccessfulTime: "2023-03-02T00:56:18Z"

