apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pv
  namespace: thingstack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: database-pv
  resources:
    requests:
      storage: 10Gi

